// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9uBi1Muh6bpVOzttTKmCs83Ku1CnvnI',
    appId: '1:150891212386:web:1f38dd8c19a26665ad2b3b',
    messagingSenderId: '150891212386',
    projectId: 'bookingapp-cac10',
    authDomain: 'bookingapp-cac10.firebaseapp.com',
    storageBucket: 'bookingapp-cac10.firebasestorage.app',
    measurementId: 'G-5HXW8D9VHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2eei5HHJr6S5QfXsLfo6kSPKzP7r0hA',
    appId: '1:150891212386:android:d54ab41b0685620bad2b3b',
    messagingSenderId: '150891212386',
    projectId: 'bookingapp-cac10',
    storageBucket: 'bookingapp-cac10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85MfQHenCRYlo7zpcvApOC_1fuoLgUXE',
    appId: '1:150891212386:ios:07093ec84cdc029ead2b3b',
    messagingSenderId: '150891212386',
    projectId: 'bookingapp-cac10',
    storageBucket: 'bookingapp-cac10.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85MfQHenCRYlo7zpcvApOC_1fuoLgUXE',
    appId: '1:150891212386:ios:07093ec84cdc029ead2b3b',
    messagingSenderId: '150891212386',
    projectId: 'bookingapp-cac10',
    storageBucket: 'bookingapp-cac10.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9uBi1Muh6bpVOzttTKmCs83Ku1CnvnI',
    appId: '1:150891212386:web:a5acc0bbcc70b02bad2b3b',
    messagingSenderId: '150891212386',
    projectId: 'bookingapp-cac10',
    authDomain: 'bookingapp-cac10.firebaseapp.com',
    storageBucket: 'bookingapp-cac10.firebasestorage.app',
    measurementId: 'G-BBC74X7BWW',
  );
}
